server:
  port: 8209

eureka:         #tells about the Eureka server details and its refresh time
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8200/eureka/
spring:
  datasource:
    url: jdbc:mysql://153.112.122.55:3306/csg_esign?useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: Volvo123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true

appconfig:
  name: cms
  pwd: csg

bjcaconfig:
  appid: 1
  uncreditcode: 913100003421701491
  templateType: 2
  templateId: 77276BDB953D44AF
  personSignsType: 2
  personSignsRole: 个人签
  personSignsCardType: 1
  enterpriseSignsType: 1
  enterpriseSignsEnterpriseName: 张三金融测试有限公司
  enterpriseSignsRole: 甲方
  businessType:
  isuseproxy: true
  keyword: 签名
  interfaceurl: https://esign-test.vfsco.net.cn:443/ec-webservice/interface/keyWordSignSealServer
